apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc
  name: grpc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30005
  selector:
    service: grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc
  name: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc
  template:
    metadata:
      labels:
        service: grpc
    spec:
      containers:
      - image: rickeand/nd064-grpc:latest
        name: grpc
        imagePullPolicy: Always
      restartPolicy: Always
